apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: password-generator-app-service-monitoring
  labels:
    app: password-generator-app
    app.kubernetes.io/instance: kube-prometheus
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: password-generator-app
      app.kubernetes.io/instance: kube-prometheus
      release: kube-prometheus
  endpoints:
  - port: metrics
    path: "/metrics"
    scrapeTimeout: 30s
  jobLabel: kube-prometheus  
  namespaceSelector:
    matchNames:
    - default  
