apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.27.0
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m

    route:
      receiver: 'SRE'
      group_by: ['alertname', 'client', 'cluster', 'component', 'k8s_cluster_name', 'cronjob', 'daemonset', 'deployment', 'dst_id', 'dst_path', 'environment', 'hpa', 'ingress', 'instance', 'job_name', 'node', 'pod', 'product', 'service_name', 'statefulset', 'team', 'topic']
      group_wait: 30s
      group_interval: 2m
      repeat_interval: 3h
      routes:
        - match:
            alertname: InfoInhibitor
          receiver: blackhole
        - match:
            alertname: Watchdog
          receiver: watchdog
        - match:
            severity: 'critical'
          receiver: 'SRE'
        - match:
            severity: 'page'
          receiver: 'SRE'
        - match:
            severity: 'info'
          receiver: 'SRE-noncritical'
        - match:
            severity: 'low'
          receiver: 'SRE-noncritical'
        - match:
            severity: 'none'
          receiver: 'SRE-noncritical'
        - match:
            severity: 'warning'
          receiver: 'SRE-noncritical'

    inhibit_rules:
      - source_match:
          severity: 'page'
        target_match:
          severity: 'low'
        equal: ['alertname']

    receivers:
      - name: blackhole
      - name: watchdog
      - name: 'SRE'
        slack_configs:
          - send_resolved: true
            channel: '#monitoring'
            api_url: 'https://hooks.slack.com/services/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'
            title: |-
              [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
              {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
                {{" "}}(
                {{- with .CommonLabels.Remove .GroupLabels.Names }}
                  {{- range $index, $label := .SortedPairs -}}
                    {{ if $index }}, {{ end }}
                    {{- $label.Name }}="{{ $label.Value -}}"
                  {{- end }}
                {{- end }}
                )
              {{- end }}
            text: >-
              {{ range .Alerts -}}
              *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
              *Description:* {{ .Annotations.description }}
              *Details:*
                {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                {{ end }}
              {{ end }}  
      - name: 'SRE-noncritical'
        slack_configs:
          - send_resolved: true
            channel: '#monitoring'
            api_url: 'https://hooks.slack.com/services/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'
            title: |-
              [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
              {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
                {{" "}}(
                {{- with .CommonLabels.Remove .GroupLabels.Names }}
                  {{- range $index, $label := .SortedPairs -}}
                    {{ if $index }}, {{ end }}
                    {{- $label.Name }}="{{ $label.Value -}}"
                  {{- end }}
                {{- end }}
                )
              {{- end }}
            text: >-
              {{ range .Alerts -}}
              *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }}
