apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service
  name: service-cluster-ip
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: service
  type: ClusterIP
status:
  loadBalancer: {}
