apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service
  name: service-node-port
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30128
  selector:
    app: service
  type: NodePort
status:
  loadBalancer: {}
