apiVersion: v1
kind: Service
metadata:
  name: hpa
  labels:
    app: hpa
spec:
  type: ClusterIP
  selector:
    app: hpa
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa
  labels:
    app: hpa
spec:
  selector:
    matchLabels:
      app: hpa
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: hpa
    spec:
      containers:
      - name: hpa
        image: thiagousa/hpa:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "10Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "2000m"
